#pragma once
#include <wx/event.h>


wxDECLARE_EVENT(EVT_SOCKET_DATA_RECEIVED_FRAME, wxThreadEvent);
wxDECLARE_EVENT(EVT_SOCKET_DATA_SEND, wxThreadEvent);
wxDECLARE_EVENT(EVT_SOCKET_DATA_RECEIVED_PANEL, wxCommandEvent);