#include "gui/customEvents.hpp"


wxDEFINE_EVENT(EVT_SOCKET_DATA_RECEIVED_FRAME, wxThreadEvent);
wxDEFINE_EVENT(EVT_SOCKET_DATA_SEND, wxThreadEvent);
wxDEFINE_EVENT(EVT_SOCKET_DATA_RECEIVED_PANEL, wxCommandEvent);